//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project___Joseph_Waldman
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarField
    {
        public int LicensePlateNumber { get; set; }
        public int CarTypeID { get; set; }
        public int CurrentKilometrage { get; set; }
        public string Picture { get; set; }
        public bool IsRepaired { get; set; }
        public bool IsAvailable { get; set; }
        public string Branch { get; set; }
    }
}
