//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project___Joseph_Waldman
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRentalField
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int LicensePlateNumber { get; set; }
        public string RentalStartDate { get; set; }
        public string ReturnCarDate { get; set; }
        public string ReturnCarDateApproval { get; set; }
    }
}
