//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project___Joseph_Waldman
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarType
    {
        public string ID { get; set; }
        public int CarTypeID { get; set; }
        public string ManufacturerName { get; set; }
        public string Model { get; set; }
        public int DailyCost { get; set; }
        public int DailyMonetaryFine { get; set; }
        public int ManufactureYear { get; set; }
        public string GearBox { get; set; }
    }
}
